apache/linkis-website

- .asf.yaml
- .github/workflows/deploy.yml
- docs/architecture/orchestrator/orchestrator_ecmp_architecture.md
- docs/development/linkis_debug.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/architecture/computation_governance_services/engine/engine_conn_manager.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/architecture/orchestrator/orchestrator_ecmp_architecture.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/cluster_deployment.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/console_user_manual.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.2/architecture/computation_governance_services/engine/engine_conn_manager.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.2/architecture/orchestrator/orchestrator_ecmp_architecture.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.2/deployment/cluster_deployment.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.2/user_guide/console_user_manual.md
- src/pages/index.jsx
- versioned_docs/version-1.0.2/architecture/orchestrator/orchestrator_ecmp_architecture.md
- versioned_docs/version-1.0.2/development/linkis_debug.md
fix some image with wrong path
add auto build action
> fix:image not found

- src/pages/index.jsx
> fix bug of home page

- docs/development/development_specification/path_usage.md
- versioned_docs/version-1.0.2/development/development_specification/path_usage.md
adjust docs title of path_usage.md
> adjust docs title

- README.md
- README_ZH.md
- community/how-to-release.md
- community/how-to-subscribe.md
- docusaurus.config.js
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-subscribe.md
- i18n/zh-CN/docusaurus-theme-classic/footer.json
adjust asf  from footer to navbar
> Adjust footer about ASF links

- docs/architecture/public_enhancement_services/context_service/context_service_listener.md
fix wrong urls of picture in context_service_listener.
> fix url in context_service_listener

- docs/engine_usage/flink.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/flink.md
I add a flink usage doc.
close #91
> add flink engine plugin usage

- docs/deployment/quick_deploy.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/quick_deploy.md
[optimize the packaging logic of Linkis](https://github.com/apache/incubator-linkis/pull/1283)
> Cooperate with packaging to modify the deployment script

- community/how-to-sign-apache-icla.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-sign-apache-icla.md
Modify English link address,Delete redundant links。
> Modify English link address

- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.3/deployment/engine_conn_plugin_installation.md
> 引擎刷新增加示例代码

- docs/deployment/start_metadatasource.md
- docs/release.md
- docs/tuning_and_troubleshooting/configuration.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/api/http/metadatamanager-api.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/involve_skywalking_into_linkis.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/start_metadatasource.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/release.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/linkis-datasource-client.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/overview.md
format the document,change wrong url.
> format the document

- src/components/Contributors.tsx
- src/pages/team/index.js
team pages add contributors info
> team pages add contributors info

- community/how-to-contribute.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute.md
> Dev fix2  modify a word

- community/how-to-write-unit-test-code.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-write-unit-test-code.md
add how to init data in database h2 tables
> Dev fix3 add how to init data in database h2 tables

- docs/engine_usage/hive.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/hive.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.2/engine_usage/hive.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.3/engine_usage/hive.md
- versioned_docs/version-1.0.2/engine_usage/hive.md
- versioned_docs/version-1.0.3/engine_usage/hive.md
分别描述3点修改位置及代码
给出显示结果以及完整配置文件范例
> hive引擎文档下增加Hive修改日志展示方法

- docs/development/linkis_debug.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/development/linkis_debug.md
> Dev Add remote debugging document

- docs/deployment/cluster_deployment.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/cluster_deployment.md
fix distribution cluster doc  error
> fix 1.1.0 doc error

- community/how-to-release.md
- community/how-to-verify.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-verify.md
> change key  download  address

- blog/2022-02-21-linkis-deploy/index.md
- docs/deployment/web_install.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2022-02-21-linkis-deploy/index.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/web_install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.3/deployment/web_install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.0/deployment/web_install.md
- versioned_docs/version-1.0.3/deployment/web_install.md
- versioned_docs/version-1.1.0/deployment/web_install.md
Modify the download address of the management console installation package
> Modify the download address of the management console installation package

- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/engine_conn_plugin_installation.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/flink.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/jdbc.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/openlookeng.md
> Improve engine documentation

- i18n/zh-CN/docusaurus-plugin-content-docs/current/architecture/add_an_engine_conn.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.0/architecture/add_an_engine_conn.md
optimize add-an-engine-conn docs 
#267
> optimize add-an-engine-conn docs

- src/components/Contributors.tsx
> [Improvement-268]Team page contributors table display optimization

- src/pages/versions/index.js
> [Bug-193] Docs version page display not centered, this pr is able to fix the page

- blog/2022-06-09-Meetup-content-review.md
- i18n/zh-CN/docusaurus-plugin-content-blog/2022-06-09-Meetup-content-review.md
> Add Meetup content 

- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.1/development/new_engine_conn.md
- versioned_docs/version-1.1.1/development/new_engine_conn.md
> Modify the documentation for creating a new engine in version 1.1.1 to be consistent with version 1.1.0

- .github/workflows/scheduled-merge.yml
The purpose of this workflow is to periodically merge "asf-staging" into "asf-site"
> Scheduled auto merge asf-staging to asf-stage

- docusaurus.config.js
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.1.json
- src/pages/index.jsx
> Show doc verson in the top bar

- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/quick_deploy.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.1/deployment/quick_deploy.md
> Fix some doc errors

- .github/workflows/auto-comment.yml
> Add auto comment bot

- blog/2022-07-04-how-to-add-auto-bot.md
- blog/authors.yml
- i18n/zh-CN/docusaurus-plugin-content-blog/2022-07-04-how-to-add-auto-bot.md
- i18n/zh-CN/docusaurus-plugin-content-blog/authors.yml
The blog titled `How to add a GitHub action for the GitHub repository` lacks the corresponding English translation. This PR adds the English translation of the blog
> Perfect an English blog

- community/how-to-contribute-to-website.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute-to-website.md
Add user list modify specification.
> Modify the official website contribution guidelines.

- docusaurus.config.js
> Version display in the top bar change to old style

- .github/actions/Auto_close_associate_issue/main.js
- .github/workflows/auto-close-issue.yml
An error occurred in this workflow when the PR is merged. This PR fix the issue.
> Fix auto closing issue bot

- community/how-to-release.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md
modify comments 'test key for apache create at 20211110' to 'for apache release create at 20211110'
> modify comments

- docusaurus.config.js
- package.json
- yarn.lock
The problem is mentioned in [link](https://github.com/facebook/docusaurus/discussions/7502#discussioncomment-2827567).
> Fix Redirection

- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/elasticsearch.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/presto.md
add es and presto engine plugin docs
> add es and presto engine plugin docs

- community/how-to-contribute-to-website.md
- i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute-to-website.md
Add English document title and path specification.
> Add path and English docs specification

- blog/2022-07-16-deploy-linkis-with-kubernetes.md
- blog/authors.yml
- i18n/zh-CN/docusaurus-plugin-content-blog/2022-07-16-deploy-linkis-with-kubernetes.md
- i18n/zh-CN/docusaurus-plugin-content-blog/authors.yml
add deploy linkis with kubernetes docs
> add deploy linkis with kubernetes

- docs/release-notes-1.1.3.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/release-notes-1.1.3.md
Fix the wrong pr link from [Linkis-2159] to [Linkis-2203]
> Fix wrong pr link

- .github/workflows/auto-close-issue.yml
Fix the error when automatically closing the issue
> Fix the error when automatically closing the issue

- docs/upgrade/upgrade_guide.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/upgrade/upgrade_guide.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.1/upgrade/upgrade_guide.md
- i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.2/upgrade/upgrade_guide.md
- versioned_docs/version-1.1.1/upgrade/upgrade_guide.md
- versioned_docs/version-1.1.2/upgrade/upgrade_guide.md
1.1.1 the upgrade script lacks content description
> fix: upgrade 1.1.1 ddl,miss engine=innodb default charset=utf8 statement 

- src/pages/home/index.js
I applied for matomo tracker and need to embed the request code in the web page to complete the site statistics.
> Add a Matomo Tracker

- src/pages/home/index.js
I applied for matomo tracker and need to embed the request code in the web page to complete the site statistics.
> Modify the Matomo Tracker

- .gitignore
- docs/deployment/web-install.md
- docs/engine_usage/elasticsearch.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/web-install.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/engine_usage/elasticsearch.md
1. add elasticsearch doc support [incubator-linkis](https://github.com/apache/incubator-linkis)
#2601
2. Optimizing web-install
> elasticsearch doc support
